
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navabar from '../../component/Navabar'
// import YourData from '../../component/Homepage'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nine | Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
     
        </body>
    </html>
  )
}
